# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8cc6b46ed44d54674b661be986e35b764a34a7bf2ad83929a6b4b75e032d8b7f0d3c3265ad05789edc26135b414938f250564a6c41cdb95f4f8430fdd51e0220

test:
  secret_key_base: f2b965c93d2b1d847b1b372434c34286c09258116d8e6715be34b5414c1f6ce3eed75930920223399b287ad3437f3ed66faf499f3e5801f83dae50b30273e9f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
